// 라벨 매핑 객체들
export const labelMappings = {
  jobType: {
    "general-labor": "보통인부",
    signal: "신호수",
    lifting: "양중",
    gombang: "곰방",
    demolition: "철거",
    carpenter: "목수",
    rebar: "철근",
    concrete: "콘크리트",
    tile: "타일",
  },
  demolitionWork: {
    "general-normal": "일반",
    "general-system": "시스템/아시바/폼자재정리",
    "general-spade": "삽질",
    "general-saw": "톱질", 
    "general-sickle": "낫질",
    "signal-pedestrian": "보행안전도우미",
    "signal-vehicle": "차량/지게차 신호수",
    "signal-fire-watch": "화기감시",
    "lifting-light": "경량자재",
    "lifting-heavy": "시멘트 등 중량자재",
    "gombang-light": "경량자재",
    "gombang-heavy": "시멘트 등 중량자재",
    "demolition-main": "철거",
    "demolition-followup": "철거 뒷일",
  },
  equipment: {
    none: "없음",
    grinder: "그라인더",
    "hammer-drill": "헤머드릴",
    "hydraulic-crusher": "유압크라샤",
  },
  // experience: {
  //   unverified: "미검증",
  //   general: "일반",
  //   intermediate: "중급",
  //   advanced: "고급",
  // },
};
